#logging.level.org.springframework = debug

spring:
  application:
    name: product-catalog-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
server:
  port: 8000

  servlet:
    context-path: /product-service
jwt:
  secret: secretkey
  expiration: 86400000


springdoc:
  swagger-ui:
    path: /swagger-ui.html
